# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85f58572dc73dc63f69709f72d2d448a2f983b860993894d5d512a8a1b94a8ec81c663f6a762221af405c120b6f2a77bf08a1bb552dbc1b3ea3f4b72f40250cf

test:
  secret_key_base: 973aaa11301caf0b981a148cba05e4e22ba5f0c1f6e71f7fc2e0c238f33ccaadb90ed4e39001677f510e451dd31e5a719e7ae1fb3b6bfd451c8c67bd099e470a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
